name: Build tests

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies packages
        run: sudo apt update && sudo apt install -y sudo rsync gcovr
      - name: Pulling repo
        uses: actions/checkout@v3
        with:
          ref: "master"
          path: "repo"
      - name: Unit testing and coverage calculation
        run: make -C repo tests